FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    wget \
    curl \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_streamlit.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir --timeout 600 -r requirements_streamlit.txt

COPY str_app.py .
COPY lpr ./lpr 

EXPOSE 8501

CMD ["streamlit", "run", "str_app.py", "--server.port=8501", "--server.address=0.0.0.0"]